### ISSUE TITLE
Each messages is received twice

### ISSUE THREAD

**Issue by arieljannai** [TPei/Random-Quotes-Telegram-Bot#2]
The picture says all:

![image](https://user-images.githubusercontent.com/3811594/29286996-a9f1bcba-813c-11e7-9730-06891e39ef29.png)

**Comment by arieljannai** [comment]
Fix:
It's not two identical messages - every command is executed twice:

![image](https://user-images.githubusercontent.com/3811594/29287100-f663ebfe-813c-11e7-8ea5-9be8db290fd2.png)

**Comment by TPei** [comment]
Hey, is that the bot I run at https://telegram.me/RickAndMortyQuoterBot or did you set up the service yourself?

**Comment by arieljannai** [comment]
Yep, it's that bot

**Comment by TPei** [comment]
Hey, apparently I had the bot running twice on the server, I fixed that. Only responds once now. Thanks for informing me :)
